---
title: "MFQ"
author: "Nisha Bharat"
date: "February 14, 2019"
output:
  html_document:
    toc: true
    theme: united
    highlight: tango
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
library(car)
library(ggplot2)
library(MASS)
library(Hmisc)
library(tidyr)
library(tidyverse)
library(dplyr)
library(plyr)
library(summarytools)
library(psych)
```

```{r include=FALSE}
mfq_twoyear <- read.csv("C:/Users/nishab/Desktop/mfq_twoyear.csv")
```

```{r include=FALSE}
mfq_twoyear <- mfq_twoyear[!is.na(mfq_twoyear$mfqc1_1_2yr),]
```

```{r include=FALSE}
mfq_twoyear$mfqc1_1_2yr <- car::recode(mfq_twoyear$mfqc1_1_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc1_2_2yr <- car::recode(mfq_twoyear$mfqc1_2_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc1_3_2yr <- car::recode(mfq_twoyear$mfqc1_3_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc1_4_2yr <- car::recode(mfq_twoyear$mfqc1_4_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc1_5_2yr <- car::recode(mfq_twoyear$mfqc1_5_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc1_6_2yr <- car::recode(mfq_twoyear$mfqc1_6_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc2_7_2yr <- car::recode(mfq_twoyear$mfqc2_7_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc2_8_2yr <- car::recode(mfq_twoyear$mfqc2_8_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc2_9_2yr <- car::recode(mfq_twoyear$mfqc2_9_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc2_10_2yr <- car::recode(mfq_twoyear$mfqc2_10_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc2_11_2yr <- car::recode(mfq_twoyear$mfqc2_11_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc2_12_2yr <- car::recode(mfq_twoyear$mfqc2_12_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc3_13_2yr <- car::recode(mfq_twoyear$mfqc3_13_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc3_14_2yr <- car::recode(mfq_twoyear$mfqc3_14_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc3_15_2yr <- car::recode(mfq_twoyear$mfqc3_15_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc4_20_2yr <- car::recode(mfq_twoyear$mfqc4_20_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc4_21_2yr <- car::recode(mfq_twoyear$mfqc4_21_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc4_22_2yr <- car::recode(mfq_twoyear$mfqc4_22_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc4_23_2yr <- car::recode(mfq_twoyear$mfqc4_23_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc4_24_2yr <- car::recode(mfq_twoyear$mfqc4_24_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc5_25_2yr <- car::recode(mfq_twoyear$mfqc5_25_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc5_26_2yr <- car::recode(mfq_twoyear$mfqc5_26_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc5_27_2yr <- car::recode(mfq_twoyear$mfqc5_27_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc5_28_2yr <- car::recode(mfq_twoyear$mfqc5_28_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc5_29_2yr <- car::recode(mfq_twoyear$mfqc5_29_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc6_30_2yr <- car::recode(mfq_twoyear$mfqc6_30_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc6_31_2yr <- car::recode(mfq_twoyear$mfqc6_31_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc6_32_2yr <- car::recode(mfq_twoyear$mfqc6_32_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc6_33_2yr <- car::recode(mfq_twoyear$mfqc6_33_2yr, "1=0; 2=1; 3=2")
mfq_twoyear$mfqc6_34_2yr <- car::recode(mfq_twoyear$mfqc6_34_2yr, "1=0; 2=1; 3=2")

```

```{r include=FALSE}
names(mfq_twoyear) 

mfq_vars_dummy <- cbind(mfq_twoyear$mfqc1_1_2yr, mfq_twoyear$mfqc1_2_2yr, mfq_twoyear$mfqc1_3_2yr, mfq_twoyear$mfqc1_4_2yr, mfq_twoyear$mfqc1_5_2yr, mfq_twoyear$mfqc1_6_2yr, mfq_twoyear$mfqc2_7_2yr, mfq_twoyear$mfqc2_8_2yr, mfq_twoyear$mfqc2_9_2yr, mfq_twoyear$mfqc2_10_2yr, mfq_twoyear$mfqc2_11_2yr, mfq_twoyear$mfqc2_12_2yr, mfq_twoyear$mfqc3_13_2yr, mfq_twoyear$mfqc3_14_2yr, mfq_twoyear$mfqc3_15_2yr, mfq_twoyear$mfqc4_20_2yr, mfq_twoyear$mfqc4_21_2yr, mfq_twoyear$mfqc4_22_2yr, mfq_twoyear$mfqc4_23_2yr, mfq_twoyear$mfqc4_24_2yr, mfq_twoyear$mfqc5_25_2yr, mfq_twoyear$mfqc5_26_2yr, mfq_twoyear$mfqc5_27_2yr, mfq_twoyear$mfqc5_28_2yr, mfq_twoyear$mfqc5_29_2yr, mfq_twoyear$mfqc6_30_2yr, mfq_twoyear$mfqc6_31_2yr, mfq_twoyear$mfqc6_32_2yr, mfq_twoyear$mfqc6_33_2yr, mfq_twoyear$mfqc6_34_2yr)
```

```{r include=FALSE}
mfq_twoyear$mfq_total_mean <- rowMeans(mfq_vars_dummy, na.rm=TRUE)
```

```{r include=FALSE}
mfq_twoyear$mfq_total_sum <- rowSums(mfq_vars_dummy, na.rm=TRUE)
```

```{r include=FALSE}
rm(mfq_vars_dummy)
```

# Descriptive statistics for two year MFQ

```{r, include=FALSE}
summarytools::descr(mfq_twoyear, style = "rmarkdown", na.rm=TRUE)
```

```{r, results='asis'}
mfqsmall <- data.frame(mfq_twoyear$mfq_total_sum)
names(mfqsmall)[names(mfqsmall) == "mfq.mfq_total_sum"] <- "MFQ Total"
```

```{r, results='asis'}
summarytools::descr(mfqsmall, style = "rmarkdown", na.rm=TRUE)
```

```{r include=FALSE}
mfq_twoyear$mfq_youth_paper_2yr <- NULL
mfq_twoyear$mfqyouth2yr_complete <- NULL
```

```{r include=FALSE}
which(mfq_twoyear == -99, arr.ind=TRUE)
```

```{r Load stuff, include=FALSE}
mfq_original <- read.csv("C:/Users/nishab/Desktop/mfq_original.csv")
names(mfq_original)[names(mfq_original) == "ï..id"] <- "id"
```

```{r include=FALSE}
View(mfq_original)
```

```{r include=FALSE}
mfq_original <- mfq_original[!(mfq_original$id==10134),]
```

# Descriptive statistics for Wave 15 MFQ

```{r echo=FALSE}
mfqsmall_original <- data.frame(mfq_original$MFQ_C_Sum)
names(mfqsmall_original)[names(mfqsmall_original) == "mfq.MFQ_C_Sum"] <- "MFQ Total"
summarytools::descr(mfqsmall_original, style = "rmarkdown", na.rm=TRUE)
```

```{r include=FALSE}
mfq <- merge(mfq_original, mfq_twoyear, by="id")
```

```{r include=FALSE}
rm(mfq_twoyear)
rm(mfq_original)
```

```{r include=FALSE}
demographic <- read.csv("C:/Users/nishab/Desktop/demographic.csv")
mfq <- merge(mfq, demographic, by="id")
rm(demographic)
```

```{r include=FALSE}
#mfq <- mfq[-c(73), ]
#mfq <- mfq[-c(113), ]
which(mfq == 88, arr.ind=TRUE)
```

```{r include=FALSE}
mfq <- mfq[!(mfq$id == "10219"),]
mfq <- mfq[!(mfq$id == "10023"),]
```

```{r include=FALSE}
mfq[mfq=="88"] <- NA
```

# Descriptive statistics on the combined dataset

```{r}
mean(mfq$MFQ_C_Sum, na.rm=TRUE)
mean(mfq$mfq_total_sum, na.rm=TRUE)

sd(mfq$MFQ_C_Sum, na.rm=TRUE)
sd(mfq$mfq_total_sum, na.rm=TRUE)

```

```{r echo=FALSE}
ggplot(mfq, aes(MFQ_C_Sum)) + geom_histogram(binwidth = 10, color="black", fill="light blue") +
  ggtitle("MFQ Wave 15 Original Histogram") + xlab("MFQ Total Score") + ylab("")

ggplot(mfq, aes(mfq_total_sum)) + geom_histogram(binwidth = 10, color="black", fill="light blue")+
  ggtitle("MFQ Wave 15 Two Year Histogram") + xlab("MFQ Total Score") + ylab("")

```

```{r echo=FALSE}
female <- mfq[ which(mfq$gender=='F'), ]
male <- mfq[ which(mfq$gender=='M'), ]

color <- "black"
fill <- "red"
ggplot(mfq, aes(x=MFQ_C_Sum, y=mfq_total_sum, fill=gender)) + 
  geom_point(aes(), shape=21, size=4) + 
  xlab("Wave 15 MFQ Total Score") +
  ylab("Two Year MFQ Total Score") +
  #theme(legend.position = "none") +
  ggtitle("Wave 15 vs 2yr Scatterplot")
```
# Is there a correlation between the old and new scores?
```{r echo=FALSE}
cor.test(mfq$MFQ_C_Sum, mfq$mfq_total_sum) 
cor.test(female$MFQ_C_Sum, female$mfq_total_sum)
cor.test(male$MFQ_C_Sum, male$mfq_total_sum)
```
# Is there a significant difference between these two scores?
```{r echo=FALSE}
t.test(mfq$MFQ_C_Sum, mfq$mfq_total_sum) 
t.test(female$MFQ_C_Sum, female$mfq_total_sum)
t.test(male$MFQ_C_Sum, male$mfq_total_sum)
```
